/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;

/**
 *
 * @author marek.b.kristof
 */
public class AjtoView extends javax.swing.JFrame {

    /**
     * Creates new form AjtoView
     */
    public AjtoView() {
        initComponents();
    }

    public JButton getBtnElsoAjto() {
        return btnElsoAjto;
    }

    public JButton getBtnHarmadikAjto() {
        return btnHarmadikAjto;
    }

    public JButton getBtnMasodikAjto() {
        return btnMasodikAjto;
    }

    public void setBtnElsoAjto(String s) {
        this.btnElsoAjto.setText(s);
    }

    public void setBtnHarmadikAjto(String s) {
        this.btnHarmadikAjto.setText(s);
    }

    public void setBtnMasodikAjto(String s) {
        this.btnMasodikAjto.setText(s);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnElsoAjto = new javax.swing.JButton();
        btnMasodikAjto = new javax.swing.JButton();
        btnHarmadikAjto = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Három Ajtó");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Melyik ajtót választod?"));
        jPanel1.setLayout(new java.awt.GridLayout());

        btnElsoAjto.setText("Kék");
        jPanel1.add(btnElsoAjto);

        btnMasodikAjto.setText("Piros");
        jPanel1.add(btnMasodikAjto);

        btnHarmadikAjto.setText("Zöld");
        jPanel1.add(btnHarmadikAjto);

        jMenu1.setText("File");

        jMenuItem1.setText("New Game");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Save");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElsoAjto;
    private javax.swing.JButton btnHarmadikAjto;
    private javax.swing.JButton btnMasodikAjto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
